name: flood_marker
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.4.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.6.1
  # geolocator: ^14.0.2
  location: ^6.0.0
  showcaseview: ^4.0.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  equatable: ^2.0.7
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  supabase: ^2.8.0
  # firebase_core: ^3.15.2
  # firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.6.3





flutter:
  uses-material-design: true



# name: event_marker
# description: "A new Flutter project."


# publish_to: 'none' 
# version: 3.24.5

# environment:
#   sdk: '>=3.5.0 <4.0.0'







# dependencies:
#   flutter:
#     sdk: flutter
#   flutter_map: ^6.1.0
#   flutter_map_marker_cluster: ^1.3.6
#   latlong2: ^0.9.0
#   supabase_flutter: ^1.10.7
#   flutter_dotenv: ^5.1.0
#   url_launcher: ^6.2.5
#   flutter_riverpod: ^2.4.9
#   geolocator: ^14.0.0
#   showcaseview: ^4.0.1
#   tutorial_coach_mark: ^1.3.1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

  
  
  
  
  
#   flutter_lints: ^5.0.0
#   riverpod_lint: ^2.3.7





# flutter:

  
  
  
#   uses-material-design: true



  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
